# Generated by Django 4.0.3 on 2022-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitneyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('source', models.TextField(default='FaceBook', max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'myapp_image',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
