# Generated by Django 4.0.3 on 2022-03-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitneyapp', '0003_alter_sermon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
